# Generated by Django 5.2.2 on 2025-09-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_browsinghistory_usercontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowsingHistory',
        ),
    ]
