# Generated by Django 5.2.4 on 2025-07-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
