# Generated by Django 5.2.4 on 2025-07-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
