# Generated by Django 5.2.2 on 2025-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_preferences'),
        ('products', '0009_product_products_tokens_product_similar_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profile_favorites', to='products.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
