# Generated by Django 5.2.2 on 2025-09-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='concerns',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
    ]
