# Generated by Django 5.2.4 on 2025-07-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('skin_types', models.CharField(max_length=100)),
                ('concerns_targeted', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image_url', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
