# Generated by Django 5.2.4 on 2025-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_types',
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('خشک', 'خشک'), ('چرب', 'چرب'), ('نرمال', 'نرمال'), ('ترکیبی', 'ترکیبی'), ('حساس', 'حساس')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
