# Generated by Django 5.2.4 on 2025-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_skin_types_product_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('آبرسان', 'آبرسان'), ('ضدآفتاب', 'ضدآفتاب'), ('ضدچروک', 'ضدچروک'), ('روشن\u200cکننده', 'روشن\u200cکننده'), ('ضدجوش', 'ضدجوش'), ('کرم شب', 'کرم شب')], max_length=50),
        ),
    ]
