# Generated by Django 5.2.4 on 2025-08-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
