# Generated by Django 5.2.2 on 2025-09-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_tokens',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='similarity_threshold',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_for',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
