# Generated by Django 5.2.2 on 2025-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_products_tokens_product_similar_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
